### ISSUE TITLE
example cant be used

### ISSUE THREAD

**Issue by huskyth** [stephane-caron/matplotlive#2]

**Comment by stephane-caron** [comment]
Thank you for reporting an issue. I just tried all examples in a fresh environment and all four worked. Can you detail which example does not work for you, and paste a terminal output with the error?

**Comment by huskyth** [comment]
i just sayed in readme file



---Original---
From: "Stéphane ***@***.***&gt;
Date: Fri, Aug 16, 2024 14:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [stephane-caron/matplotlive] example cant be used (Issue #2)




 
Thank you for reporting an issue. I just tried all examples in a fresh environment and all four worked. Can you detail which example does not work for you, and paste a terminal output with the error?

**Comment by stephane-caron** [comment]
Oh, you must have been running the example from within the git repository. Can you `git pull` and try again? It should be fixed now.

**Comment by huskyth** [comment]
fine&nbsp;



---Original---
From: "Stéphane ***@***.***&gt;
Date: Fri, Aug 16, 2024 15:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [stephane-caron/matplotlive] example cant be used (Issue #2)




 
Oh, you must have been running the example from within the git repository. Can you git pull and try again? It should be fixed now.

**Comment by stephane-caron** [comment]
Great! Thank you again for reporting this issue :+1:
